/**
 * @quartz-nextjs/quartz-nextjs
 *
 * Quartz plugins and components for Next.js
 *
 * This package re-exports Quartz plugins and provides Next.js-specific utilities.
 * The Quartz code is synced from the upstream repository using `bun run sync-quartz`.
 */

// Version info (auto-generated by sync-quartz script)
export * from './version'

// Re-export all Quartz plugins
// Import paths match Quartz's structure: quartz/plugins/...
export * from '../quartz/plugins/transformers/index'
export * from '../quartz/plugins/filters/index'

// Utilities
export * from '../quartz/util/path'
export * from '../quartz/util/resources'

// Config types
export type { QuartzConfig } from '../quartz/cfg'

// Next.js specific utilities
export * from './next/index'
