// Auto-generated by sync-quartz.ts
// Last synced: 2026-01-01T12:12:03.510Z

export const QUARTZ_VERSION = '4.5.2'
export const QUARTZ_NEXTJS_VERSION = '0.1.0'
export const LAST_SYNC = '2026-01-01T12:12:03.510Z'
