#!/usr/bin/env bun

/**
 * Quartz Sync Script
 *
 * Automatically syncs with upstream Quartz repository to get latest features.
 *
 * Usage:
 *   bun run sync-quartz           # Clone/update and copy files
 *   bun run sync-quartz --dry-run # Check what would be synced
 */

import { $, write } from 'bun'
import { existsSync, rmSync } from 'fs'
import { cp, readFile, writeFile } from 'fs/promises'
import { join } from 'path'

const QUARTZ_REPO = 'https://github.com/jackyzha0/quartz.git'
const UPSTREAM_DIR = './upstream/quartz'
const PACKAGE_DIR = './packages/nuartz'
const QUARTZ_DIR = './packages/nuartz/quartz'  // Quartz-style nested structure

const isDryRun = process.argv.includes('--dry-run')

// Files/folders to sync from Quartz (now goes into quartz/ subdirectory)
const SYNC_TARGETS = [
  { from: 'quartz/plugins', to: 'plugins' },
  { from: 'quartz/util', to: 'util' },
  { from: 'quartz/processors', to: 'processors' },
  { from: 'quartz/components', to: 'components' },
  { from: 'quartz/cfg.ts', to: 'cfg.ts' },
  { from: 'quartz/i18n', to: 'i18n' },
  { from: 'quartz/styles', to: 'styles' },
  { from: 'quartz/static', to: 'static' },
]

console.log('🔄 Quartz Sync Tool\n')

async function main() {
  try {
    // Step 1: Clone or update Quartz
    await cloneOrUpdateQuartz()

    // Step 2: Get Quartz version
    const version = await getQuartzVersion()
    console.log(`📦 Quartz version: ${version}\n`)

    // Step 3: Copy files
    await syncFiles()

    // Step 4: Update version file
    if (!isDryRun) {
      await updateVersionFile(version)
    }

    console.log('\n✅ Sync completed successfully!')
    console.log('\nNext steps:')
    console.log('  1. Review changes: git diff packages/nuartz')
    console.log('  2. Run tests: bun test')
    console.log('  3. Commit: git commit -m "chore: sync with Quartz v' + version + '"')

  } catch (error) {
    console.error('❌ Error:', error)
    process.exit(1)
  }
}

async function cloneOrUpdateQuartz() {
  if (existsSync(UPSTREAM_DIR)) {
    console.log('📥 Updating Quartz from upstream...')
    if (!isDryRun) {
      await $`cd ${UPSTREAM_DIR} && git pull origin v4`
    }
    console.log('✓ Updated\n')
  } else {
    console.log('📥 Cloning Quartz repository...')
    if (!isDryRun) {
      // Create upstream directory
      await $`mkdir -p upstream`
      // Clone with specific branch
      await $`git clone --depth 1 --branch v4 ${QUARTZ_REPO} ${UPSTREAM_DIR}`
    }
    console.log('✓ Cloned\n')
  }
}

async function getQuartzVersion(): Promise<string> {
  try {
    const packageJsonPath = join(UPSTREAM_DIR, 'package.json')
    const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf-8'))
    return packageJson.version || 'unknown'
  } catch {
    return 'unknown'
  }
}

async function syncFiles() {
  console.log('📋 Syncing files...\n')

  for (const target of SYNC_TARGETS) {
    const sourcePath = join(UPSTREAM_DIR, target.from)
    const destPath = join(QUARTZ_DIR, target.to)  // Changed: now goes into quartz/ subdirectory

    if (!existsSync(sourcePath)) {
      console.log(`⚠️  Skipping ${target.from} (not found in upstream)`)
      continue
    }

    console.log(`  ${target.from} → packages/nuartz/quartz/${target.to}`)

    if (!isDryRun) {
      // Remove existing
      if (existsSync(destPath)) {
        rmSync(destPath, { recursive: true, force: true })
      }

      // Copy new
      await cp(sourcePath, destPath, { recursive: true })
    }
  }

  console.log('\n✓ Files synced')
}

async function updateVersionFile(version: string) {
  const versionFilePath = join(PACKAGE_DIR, 'src', 'version.ts')
  const content = `// Auto-generated by sync-quartz.ts
// Last synced: ${new Date().toISOString()}

export const QUARTZ_VERSION = '${version}'
export const QUARTZ_NEXTJS_VERSION = '0.1.0'
export const LAST_SYNC = '${new Date().toISOString()}'
`

  await writeFile(versionFilePath, content, 'utf-8')
  console.log(`\n✓ Updated version.ts (Quartz ${version})`)
}

// Run
main()
